using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EventSourceProxy
{
	/// <summary>
	/// Enumerates the types of mappings that we use.
	/// </summary>
	public enum ParameterMappingType
	{
		/// <summary>
		/// A parameter that has been passed in.
		/// </summary>
		Parameter,

		/// <summary>
		/// A context parameter that should be generated by calling the context provider.
		/// </summary>
		Context,

		/// <summary>
		/// A return value that is on the stack, not an input parameter.
		/// </summary>
		ReturnValue
	}
}
